CREATE TABLE IF NOT EXISTS `user` (
  `id` varchar(16) NOT NULL DEFAULT '',
  `username` varchar(20) DEFAULT NULL,
  `fullname` varchar(150) DEFAULT NULL,
  `university` varchar(50) DEFAULT NULL,
  `major` varchar(50) DEFAULT NULL,
  `citizen_id` varchar(50) DEFAULT NULL,
  `student_id` varchar(50) DEFAULT NULL,
  `password` varchar(70) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `gender` enum('male','female') DEFAULT 'male',
  `manual` tinyint(1) DEFAULT '0',
  `secret` varchar(50) DEFAULT NULL,
  `source` varchar(30) DEFAULT NULL,
  `socmed` varchar(30) DEFAULT NULL,
  `citizen_card` varchar(50) DEFAULT NULL,
  `citizen_selfie` varchar(50) DEFAULT NULL,
  `student_card` varchar(50) DEFAULT NULL,
  `merchant` tinyint(1) DEFAULT NULL,
  `time_signup` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `time_signin` timestamp NULL DEFAULT NULL,
  `activated` tinyint(1) DEFAULT '0',
  `id_socmed` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
