// Code generated by mockery v1.0.0
package mocks

import category "github.com/NgulikinApp/luffy/category"
import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: num, cursor
func (_m *Repository) Fetch(num int64, cursor int64) ([]*category.Category, error) {
	ret := _m.Called(num, cursor)

	var r0 []*category.Category
	if rf, ok := ret.Get(0).(func(int64, int64) []*category.Category); ok {
		r0 = rf(num, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*category.Category)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64, int64) error); ok {
		r1 = rf(num, cursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
